<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="date" content="2017-11-06" />

<title>expss: Tables with Labels in R</title>

<script src="index_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="index_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="index_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="index_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="index_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="index_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="index_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="index_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="index_files/navigation-1.1/tabsets.js"></script>
<link href="index_files/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="index_files/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">expss: Tables with Labels in R</h1>
<h4 class="date"><em>2017-11-06</em></h4>

</div>


<p><a href="https://cran.r-project.org/package=expss"><img src="http://www.r-pkg.org/badges/version/expss" alt="CRAN_Status_Badge" /></a> <a href="https://cran.rstudio.com/web/packages/expss/index.html"><img src="https://cranlogs.r-pkg.org/badges/expss" /></a> <a href="https://cran.rstudio.com/web/packages/expss/index.html"><img src="https://cranlogs.r-pkg.org/badges/grand-total/expss" /></a> <a href="https://codecov.io/github/gdemin/expss?branch=master"><img src="https://img.shields.io/codecov/c/github/gdemin/expss/master.svg" alt="Coverage Status" /></a></p>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p><code>expss</code> package provides tabulation functions with support for ‘SPSS’-style labels, multiple / nested banners, weights, multiple-response variables and significance testing. There are facilities for nice output of tables in ‘knitr’, R notebooks, ‘Shiny’ and ‘Jupyter’ notebooks. Proper methods for labelled variables add value labels support to base R functions and to some functions from other packages. Additionally, the package offers useful functions for data processing in marketing research / social surveys - popular data transformation functions from ‘SPSS’ Statistics (‘RECODE’, ‘COUNT’, ‘COMPUTE’, ‘DO IF’, etc.) and ‘Excel’ (‘COUNTIF’, ‘VLOOKUP’, etc.). Package is intended to help people to move data processing from ‘Excel’/‘SPSS’ to R. See examples below. You can get help about any function by typing <code>?function_name</code> in the R console.</p>
<div id="links" class="section level3">
<h3>Links</h3>
<ul>
<li><a href="http://gdemin.github.io/expss/">Online introduction (current page)</a></li>
<li><a href="https://cran.r-project.org/package=expss">expss on CRAN</a></li>
<li><a href="https://github.com/gdemin/expss">expss on Github</a></li>
<li><a href="https://github.com/gdemin/expss/issues">Issues</a></li>
</ul>
</div>
</div>
<div id="installation" class="section level2">
<h2>Installation</h2>
<p><code>expss</code> is on CRAN, so for installation you can print in the console <code>install.packages(&quot;expss&quot;)</code>.</p>
</div>
<div id="cross-tablulation-examples" class="section level2">
<h2>Cross-tablulation examples</h2>
<p>We will use for demonstartion well-known <code>mtcars</code> dataset. Let’s start with adding labels to the dataset. Then we can continue with tables creation.</p>
<pre class="r"><code>library(expss)
data(mtcars)
mtcars = apply_labels(mtcars,
                      mpg = &quot;Miles/(US) gallon&quot;,
                      cyl = &quot;Number of cylinders&quot;,
                      disp = &quot;Displacement (cu.in.)&quot;,
                      hp = &quot;Gross horsepower&quot;,
                      drat = &quot;Rear axle ratio&quot;,
                      wt = &quot;Weight (1000 lbs)&quot;,
                      qsec = &quot;1/4 mile time&quot;,
                      vs = &quot;Engine&quot;,
                      vs = c(&quot;V-engine&quot; = 0,
                             &quot;Straight engine&quot; = 1),
                      am = &quot;Transmission&quot;,
                      am = c(&quot;Automatic&quot; = 0,
                             &quot;Manual&quot;=1),
                      gear = &quot;Number of forward gears&quot;,
                      carb = &quot;Number of carburetors&quot;
)</code></pre>
<p>For quick cross-tabulation there are <code>fre</code> and <code>cro</code> family of function. For simplicity we demonstrate here only <code>cro_cpct</code> which caluclates column percent. Documentation for other functions, such as <code>cro_cases</code> for counts, <code>cro_rpct</code> for row percent, <code>cro_tpct</code> for table percent and <code>cro_fun</code> for custom summary functions can be seen by typing <code>?cro</code> and <code>?cro_fun</code> in the console.</p>
<pre class="r"><code># &#39;cro&#39; examples
# Table with multiple banners (column %).
cro_cpct(mtcars$cyl, list(total(), mtcars$am, mtcars$vs))</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Transmission&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Engine&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Automatic&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Manual&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;V-engine&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Straight engine&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='8' style='font-weight: 900;'>&nbsp;Number of cylinders&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;4&nbsp;</td>
<td style='text-align: right;'>34.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>15.8</td>
<td style='text-align: right;'>61.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>5.6</td>
<td style='text-align: right;'>71.4</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;6&nbsp;</td>
<td style='text-align: right;'>21.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>21.1</td>
<td style='text-align: right;'>23.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
<td style='text-align: right;'>28.6</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;8&nbsp;</td>
<td style='text-align: right;'>43.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>63.2</td>
<td style='text-align: right;'>15.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>77.8</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>32</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>19</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>13</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>18</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>14</td>
</tr>
</tbody>
</table>
<pre class="r"><code># or, the same result with another notation
mtcars %&gt;% calc_cro_cpct(cyl, list(total(), am, vs))</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Transmission&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Engine&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Automatic&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Manual&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;V-engine&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Straight engine&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='8' style='font-weight: 900;'>&nbsp;Number of cylinders&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;4&nbsp;</td>
<td style='text-align: right;'>34.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>15.8</td>
<td style='text-align: right;'>61.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>5.6</td>
<td style='text-align: right;'>71.4</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;6&nbsp;</td>
<td style='text-align: right;'>21.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>21.1</td>
<td style='text-align: right;'>23.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
<td style='text-align: right;'>28.6</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;8&nbsp;</td>
<td style='text-align: right;'>43.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>63.2</td>
<td style='text-align: right;'>15.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>77.8</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>32</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>19</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>13</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>18</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>14</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Table with nested banners (column %).          
mtcars %&gt;% calc_cro_cpct(cyl, list(total(), am %nest% vs))     </code></pre>
<p><table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='5' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Transmission&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='1' style='font-weight: 900; text-align: center;'></th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Automatic&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Manual&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='1' style='font-weight: 900; text-align: center;'></th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Engine&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Engine&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;V-engine&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Straight engine&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;V-engine&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Straight engine&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='8' style='font-weight: 900;'>&nbsp;Number of cylinders&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;4&nbsp;</td>
<td style='text-align: right;'>34.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'>42.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
<td style='text-align: right;'>100</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;6&nbsp;</td>
<td style='text-align: right;'>21.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'>57.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50.0</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;8&nbsp;</td>
<td style='text-align: right;'>43.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.3</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>32</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>12</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>7</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>6</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>7</td>
</tr>
</tbody>
</table> We have more sophisticated interface for table construction with <code>magrittr</code> piping. Table construction consists of at least of three functions chained with pipe operator: <code>%&gt;%</code>. At first we need to specify variables for which statistics will be computed with <code>tab_cells</code>. Secondary, we calculate statistics with one of the <code>tab_stat_*</code> functions. And last, we finalize table creation with <code>tab_pivot</code>, e. g.: <code>dataset %&gt;% tab_cells(variable) %&gt;% tab_stat_cases() %&gt;% tab_pivot()</code>. After that we can optionally sort table with <code>tab_sort_asc</code>, drop empty rows/columns with <code>drop_rc</code> and transpose with <code>tab_transpose</code>. Resulting table is just a <code>data.frame</code> so we can use usual R operations on it. Detailed documentation for table creation can be seen via <code>?tables</code>. For significance testing see <code>?significance</code>. Generally, tables automatically translated to HTML for output in knitr or Jupyter notebooks. However, if we want HTML output in the R notebooks or in the RStudio viewer we need to set options for that: <code>expss_output_rnotebook()</code> or <code>expss_output_viewer()</code>.</p>
<pre class="r"><code># simple example
mtcars %&gt;% 
    tab_cells(cyl) %&gt;% 
    tab_cols(total(), am) %&gt;% 
    tab_stat_cpct() %&gt;% 
    tab_pivot()</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Transmission&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Automatic&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Manual&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='5' style='font-weight: 900;'>&nbsp;Number of cylinders&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;4&nbsp;</td>
<td style='text-align: right;'>34.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>15.8</td>
<td style='text-align: right;'>61.5</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;6&nbsp;</td>
<td style='text-align: right;'>21.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>21.1</td>
<td style='text-align: right;'>23.1</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;8&nbsp;</td>
<td style='text-align: right;'>43.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>63.2</td>
<td style='text-align: right;'>15.4</td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>32</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>19</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>13</td>
</tr>
</tbody>
</table>
<pre class="r"><code># if we need caption then we use &#39;htmlTable&#39;
mtcars %&gt;% 
    tab_cells(mpg, disp, hp, wt, qsec) %&gt;%
    tab_cols(total(), am) %&gt;% 
    tab_stat_mean_sd_n() %&gt;%
    tab_last_sig_means(subtable_marks = &quot;both&quot;) %&gt;% 
    tab_pivot() %&gt;% 
    htmlTable(caption = &quot;Table with summary statistics and significance marks.&quot;)</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr><td colspan='6' style='text-align: left;'>
Table with summary statistics and significance marks.</td></tr>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Transmission&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='1' style='font-weight: 900; text-align: center;'></th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Automatic&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Manual&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;A&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;B&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='6' style='font-weight: 900;'>&nbsp;Miles/(US) gallon&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Mean&nbsp;</td>
<td style='text-align: right;'> 20.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 17.1 < B</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 24.4 > A</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Std. dev.&nbsp;</td>
<td style='text-align: right;'>  6.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>  3.8   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>  6.2   &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Unw. valid N&nbsp;</td>
<td style='text-align: right;'> 32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 19.0   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 13.0   &nbsp;</td>
</tr> 
<tr><td colspan='6' style='font-weight: 900;'>&nbsp;Displacement (cu.in.)&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Mean&nbsp;</td>
<td style='text-align: right;'>230.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>290.4 > B</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>143.5 < A</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Std. dev.&nbsp;</td>
<td style='text-align: right;'>123.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>110.2   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 87.2   &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Unw. valid N&nbsp;</td>
<td style='text-align: right;'> 32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 19.0   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 13.0   &nbsp;</td>
</tr> 
<tr><td colspan='6' style='font-weight: 900;'>&nbsp;Gross horsepower&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Mean&nbsp;</td>
<td style='text-align: right;'>146.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>160.3   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>126.8   &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Std. dev.&nbsp;</td>
<td style='text-align: right;'> 68.6</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 53.9   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 84.1   &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Unw. valid N&nbsp;</td>
<td style='text-align: right;'> 32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 19.0   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 13.0   &nbsp;</td>
</tr> 
<tr><td colspan='6' style='font-weight: 900;'>&nbsp;Weight (1000 lbs)&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Mean&nbsp;</td>
<td style='text-align: right;'>  3.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>  3.8 > B</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>  2.4 < A</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Std. dev.&nbsp;</td>
<td style='text-align: right;'>  1.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>  0.8   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>  0.6   &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Unw. valid N&nbsp;</td>
<td style='text-align: right;'> 32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 19.0   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 13.0   &nbsp;</td>
</tr> 
<tr><td colspan='6' style='font-weight: 900;'>&nbsp;1/4 mile time&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Mean&nbsp;</td>
<td style='text-align: right;'> 17.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 18.2   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 17.4   &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Std. dev.&nbsp;</td>
<td style='text-align: right;'>  1.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>  1.8   &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>  1.8   &nbsp;</td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;Unw. valid N&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'> 32.0</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'> 19.0   &nbsp;</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'> 13.0   &nbsp;</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Table with the same summary statistics. Statistics labels in columns.
mtcars %&gt;% 
    tab_cells(mpg, disp, hp, wt, qsec) %&gt;%
    tab_cols(total(label = &quot;#Total| |&quot;), am) %&gt;% 
    tab_stat_fun(Mean = w_mean, &quot;Std. dev.&quot; = w_sd, &quot;Valid N&quot; = w_n, method = list) %&gt;%
    tab_pivot()</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='7' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Transmission&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp; &nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Automatic&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Manual&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Mean&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Std. dev.&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Valid N&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Mean&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Std. dev.&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Valid N&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Mean&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Std. dev.&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Valid N&nbsp;</th>
</tr>
</thead>
<tbody>
<tr>
<td style='text-align: left;'>&nbsp;Miles/(US) gallon&nbsp;</td>
<td style='text-align: right;'>20.1</td>
<td style='text-align: right;'>6.0</td>
<td style='text-align: right;'>32</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>17.1</td>
<td style='text-align: right;'>3.8</td>
<td style='text-align: right;'>19</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>24.4</td>
<td style='text-align: right;'>6.2</td>
<td style='text-align: right;'>13</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Displacement (cu.in.)&nbsp;</td>
<td style='text-align: right;'>230.7</td>
<td style='text-align: right;'>123.9</td>
<td style='text-align: right;'>32</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>290.4</td>
<td style='text-align: right;'>110.2</td>
<td style='text-align: right;'>19</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>143.5</td>
<td style='text-align: right;'>87.2</td>
<td style='text-align: right;'>13</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Gross horsepower&nbsp;</td>
<td style='text-align: right;'>146.7</td>
<td style='text-align: right;'>68.6</td>
<td style='text-align: right;'>32</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>160.3</td>
<td style='text-align: right;'>53.9</td>
<td style='text-align: right;'>19</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>126.8</td>
<td style='text-align: right;'>84.1</td>
<td style='text-align: right;'>13</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Weight (1000 lbs)&nbsp;</td>
<td style='text-align: right;'>3.2</td>
<td style='text-align: right;'>1.0</td>
<td style='text-align: right;'>32</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>3.8</td>
<td style='text-align: right;'>0.8</td>
<td style='text-align: right;'>19</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>2.4</td>
<td style='text-align: right;'>0.6</td>
<td style='text-align: right;'>13</td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;1/4 mile time&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>17.8</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>1.8</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>32</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>18.2</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>1.8</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>19</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>17.4</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>1.8</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>13</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Different statistics for different variables.
mtcars %&gt;%
    tab_cols(total(), vs) %&gt;%
    tab_cells(mpg) %&gt;% 
    tab_stat_mean() %&gt;% 
    tab_stat_valid_n() %&gt;% 
    tab_cells(am) %&gt;%
    tab_stat_cpct(total_row_position = &quot;none&quot;, label = &quot;col %&quot;) %&gt;%
    tab_stat_rpct(total_row_position = &quot;none&quot;, label = &quot;row %&quot;) %&gt;%
    tab_stat_tpct(total_row_position = &quot;none&quot;, label = &quot;table %&quot;) %&gt;%
    tab_pivot(stat_position = &quot;inside_rows&quot;) </code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-top: 2px solid grey; text-align: center;'></th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Engine&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;V-engine&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Straight engine&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='7' style='font-weight: 900;'>&nbsp;Miles/(US) gallon&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Mean&nbsp;</td>
<td style='text-align: left;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>20.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.6</td>
<td style='text-align: right;'>24.6</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Valid N&nbsp;</td>
<td style='text-align: left;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>18.0</td>
<td style='text-align: right;'>14.0</td>
</tr> 
<tr><td colspan='7' style='font-weight: 900;'>&nbsp;Transmission&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Automatic&nbsp;</td>
<td style='text-align: left;'>&nbsp;col %&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>59.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>66.7</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'>&nbsp;row %&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>63.2</td>
<td style='text-align: right;'>36.8</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'>&nbsp;table %&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>59.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>37.5</td>
<td style='text-align: right;'>21.9</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Manual&nbsp;</td>
<td style='text-align: left;'>&nbsp;col %&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>40.6</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.3</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'>&nbsp;row %&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>46.2</td>
<td style='text-align: right;'>53.8</td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;table %&nbsp;</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>40.6</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>18.8</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>21.9</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Table with split by rows and with custom totals.
mtcars %&gt;% 
    tab_cells(cyl) %&gt;% 
    tab_cols(total(), vs) %&gt;% 
    tab_rows(am) %&gt;% 
    tab_stat_cpct(total_row_position = &quot;above&quot;,
                  total_label = c(&quot;number of cases&quot;, &quot;row %&quot;),
                  total_statistic = c(&quot;u_cases&quot;, &quot;u_rpct&quot;)) %&gt;% 
    tab_pivot()</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='2' style='font-weight: 900; border-top: 2px solid grey; text-align: center;'></th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Engine&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;V-engine&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Straight engine&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='8' style='font-weight: 900;'>&nbsp;Transmission&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Automatic&nbsp;</td>
<td style='text-align: left;'>&nbsp;Number of cylinders&nbsp;</td>
<td style='text-align: left;'>&nbsp;#number of cases&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>19</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>12</td>
<td style='text-align: right;'>7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'></td>
<td style='text-align: left;'>&nbsp;#row %&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>63.2</td>
<td style='text-align: right;'>36.8</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'></td>
<td style='text-align: left;'>&nbsp;4&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>15.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'>42.9</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'></td>
<td style='text-align: left;'>&nbsp;6&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>21.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'>57.1</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'></td>
<td style='text-align: left;'>&nbsp;8&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>63.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100.0</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Manual&nbsp;</td>
<td style='text-align: left;'>&nbsp;Number of cylinders&nbsp;</td>
<td style='text-align: left;'>&nbsp;#number of cases&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>13</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>6</td>
<td style='text-align: right;'>7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'></td>
<td style='text-align: left;'>&nbsp;#row %&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>46.2</td>
<td style='text-align: right;'>53.8</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'></td>
<td style='text-align: left;'>&nbsp;4&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>61.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
<td style='text-align: right;'>100.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;</td>
<td style='text-align: left;'></td>
<td style='text-align: left;'>&nbsp;6&nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>23.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50.0</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: left;'></td>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;8&nbsp;</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>15.4</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>33.3</td>
<td style='border-bottom: 2px solid grey; text-align: right;'></td>
</tr>
</tbody>
</table>
<pre class="r"><code># Linear regression by groups.
mtcars %&gt;% 
    tab_cells(sheet(mpg, disp, hp, wt, qsec)) %&gt;% 
    tab_cols(total(label = &quot;#Total| |&quot;), am) %&gt;% 
    tab_stat_fun_df(
        function(x){
            frm = reformulate(&quot;.&quot;, response = names(x)[1])
            model = lm(frm, data = x)
            sheet(&#39;Coef.&#39; = coef(model), 
                  confint(model)
            )
        }    
    ) %&gt;% 
    tab_pivot() </code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='7' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Transmission&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp; &nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Automatic&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Manual&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Coef.&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;2.5 %&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;97.5 %&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Coef.&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;2.5 %&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;97.5 %&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Coef.&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;2.5 %&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;97.5 %&nbsp;</th>
</tr>
</thead>
<tbody>
<tr>
<td style='text-align: left;'>&nbsp;(Intercept)&nbsp;</td>
<td style='text-align: right;'>27.3</td>
<td style='text-align: right;'>9.6</td>
<td style='text-align: right;'>45.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>21.8</td>
<td style='text-align: right;'>-1.9</td>
<td style='text-align: right;'>45.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>13.3</td>
<td style='text-align: right;'>-21.9</td>
<td style='text-align: right;'>48.4</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;`Displacement (cu.in.)`&nbsp;</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>0.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>0.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>-0.1</td>
<td style='text-align: right;'>0.1</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;`Gross horsepower`&nbsp;</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>-0.1</td>
<td style='text-align: right;'>0.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>-0.1</td>
<td style='text-align: right;'>0.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>0.0</td>
<td style='text-align: right;'>0.1</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;`Weight (1000 lbs)`&nbsp;</td>
<td style='text-align: right;'>-4.6</td>
<td style='text-align: right;'>-7.2</td>
<td style='text-align: right;'>-2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>-2.3</td>
<td style='text-align: right;'>-5.0</td>
<td style='text-align: right;'>0.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>-7.7</td>
<td style='text-align: right;'>-12.5</td>
<td style='text-align: right;'>-2.9</td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;`1/4 mile time`&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>0.5</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>-0.4</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>1.5</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>0.4</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>-0.7</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>1.6</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>1.6</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>-0.2</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>3.4</td>
</tr>
</tbody>
</table>
</div>
<div id="example-of-data-processing-with-multiple-response-variables" class="section level2">
<h2>Example of data processing with multiple-response variables</h2>
<p>Here we use truncated dataset with data from product test of two samples of chocolate sweets. 150 respondents tested two kinds of sweets (codenames: VSX123 and SDF546). Sample was divided into two groups (cells) of 75 respondents in each group. In cell 1 product VSX123 was presented first and then SDF546. In cell 2 sweets were presented in reversed order. Questions about respondent impressions about first product are in the block A (and about second tested product in the block B). At the end of the questionnaire there was a question about the preferences between sweets.</p>
<p>List of variables:</p>
<ul>
<li><code>id</code> Respondent Id</li>
<li><code>cell</code> First tested product (cell number)</li>
<li><code>s2a</code> Age</li>
<li><code>a1_1-a1_6</code> What did you like in these sweets? Multiple response. First tested product</li>
<li><code>a22</code> Overall quality. First tested product</li>
<li><code>b1_1-b1_6</code> What did you like in these sweets? Multiple response. Second tested product</li>
<li><code>b22</code> Overall quality. Second tested product</li>
<li><code>c1</code> Preferences</li>
</ul>
<pre class="r"><code>data(product_test)

w = product_test # shorter name to save some keystrokes

# here we recode variables from first/second tested product to separate variables for each product according to their cells
# &#39;h&#39; variables - VSX123 sample, &#39;p&#39; variables - &#39;SDF456&#39; sample
# also we recode preferences from first/second product to true names
# for first cell there are no changes, for second cell we should exchange 1 and 2.
w = w %&gt;% 
    do_if(cell == 1, {
        recode(a1_1 %to% a1_6, other ~ copy) %into% (h1_1 %to% h1_6)
        recode(b1_1 %to% b1_6, other ~ copy) %into% (p1_1 %to% p1_6)
        recode(a22, other ~ copy) %into% h22
        recode(b22, other ~ copy) %into% p22
        c1r = c1
    }) %&gt;% 
    do_if(cell == 2, {
        recode(a1_1 %to% a1_6, other ~ copy) %into% (p1_1 %to% p1_6)
        recode(b1_1 %to% b1_6, other ~ copy) %into% (h1_1 %to% h1_6)
        recode(a22, other ~ copy) %into% p22
        recode(b22, other ~ copy) %into% h22
        recode(c1, 1 ~ 2, 2 ~ 1, other ~ copy) %into% c1r
    }) %&gt;% 
    compute({
        # recode age by groups
        age_cat = recode(s2a, lo %thru% 25 ~ 1, lo %thru% hi ~ 2)
        # count number of likes
        # codes 2 and 99 are ignored.
        h_likes = count_row_if(1 | 3 %thru% 98, h1_1 %to% h1_6) 
        p_likes = count_row_if(1 | 3 %thru% 98, p1_1 %to% p1_6) 
    })

# here we prepare labels for future usage
codeframe_likes = num_lab(&quot;
    1 Liked everything
    2 Disliked everything
    3 Chocolate
    4 Appearance
    5 Taste
    6 Stuffing
    7 Nuts
    8 Consistency
    98 Other
    99 Hard to answer
&quot;)

overall_liking_scale = num_lab(&quot;
    1 Extremely poor 
    2 Very poor
    3 Quite poor
    4 Neither good, nor poor
    5 Quite good
    6 Very good
    7 Excellent
&quot;)

w = apply_labels(w, 
    c1r = &quot;Preferences&quot;,
    c1r = num_lab(&quot;
        1 VSX123 
        2 SDF456
        3 Hard to say
    &quot;),
    
    age_cat = &quot;Age&quot;,
    age_cat = c(&quot;18 - 25&quot; = 1, &quot;26 - 35&quot; = 2),
    
    h1_1 = &quot;Likes. VSX123&quot;,
    p1_1 = &quot;Likes. SDF456&quot;,
    h1_1 = codeframe_likes,
    p1_1 = codeframe_likes,
    
    h_likes = &quot;Number of likes. VSX123&quot;,
    p_likes = &quot;Number of likes. SDF456&quot;,
    
    h22 = &quot;Overall quality. VSX123&quot;,
    p22 = &quot;Overall quality. SDF456&quot;,
    h22 = overall_liking_scale,
    p22 = overall_liking_scale
)</code></pre>
<p>Are there any significant differences between preferences? Yes, difference is significant.</p>
<pre class="r"><code># &#39;tab_mis_val(3)&#39; remove &#39;hard to say&#39; from vector 
w %&gt;% tab_cols(total(), age_cat) %&gt;% 
      tab_cells(c1r) %&gt;% 
      tab_mis_val(3) %&gt;% 
      tab_stat_cases() %&gt;% 
      tab_last_sig_cases() %&gt;% 
      tab_pivot()</code></pre>
<p><table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Age&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;18 - 25&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;26 - 35&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='5' style='font-weight: 900;'>&nbsp;Preferences&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;VSX123&nbsp;</td>
<td style='text-align: right;'>94.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>46.0</td>
<td style='text-align: right;'>48.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;SDF456&nbsp;</td>
<td style='text-align: right;'>50.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>22.0</td>
<td style='text-align: right;'>28.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Hard to say&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;#Chi-squared p-value&nbsp;</td>
<td style='text-align: right;'><0.05</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> (warn.)</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>144.0</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>68.0</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>76.0</td>
</tr>
</tbody>
</table> Further we calculate distribution of answers in the survey questions.</p>
<pre class="r"><code># lets specify repeated parts of table creation chains
banner = w %&gt;% tab_cols(total(), age_cat, c1r) 
# column percent with significance
tab_cpct_sig = . %&gt;% tab_stat_cpct() %&gt;% 
                    tab_last_sig_cpct(sig_labels = paste0(&quot;&lt;b&gt;&quot;,LETTERS, &quot;&lt;/b&gt;&quot;))

# means with siginifcance
tab_means_sig = . %&gt;% tab_stat_mean_sd_n(labels = c(&quot;&lt;b&gt;&lt;u&gt;Mean&lt;/u&gt;&lt;/b&gt;&quot;, &quot;sd&quot;, &quot;N&quot;)) %&gt;% 
                      tab_last_sig_means(
                          sig_labels = paste0(&quot;&lt;b&gt;&quot;,LETTERS, &quot;&lt;/b&gt;&quot;),   
                          keep = &quot;means&quot;)

# Preferences
banner %&gt;% 
    tab_cells(c1r) %&gt;% 
    tab_cpct_sig() %&gt;% 
    tab_pivot() </code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Age&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='5' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Preferences&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='1' style='font-weight: 900; text-align: center;'></th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;18 - 25&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;26 - 35&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;VSX123&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;SDF456&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Hard to say&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>A</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>B</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>A</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>B</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>C</b>&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='12' style='font-weight: 900;'>&nbsp;Preferences&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;VSX123&nbsp;</td>
<td style='text-align: right;'>62.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>65.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>60.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;SDF456&nbsp;</td>
<td style='text-align: right;'>33.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>31.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>35.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Hard to say&nbsp;</td>
<td style='text-align: right;'> 4.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>100.0</td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>150</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>70</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>80</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>94</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>50</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>6</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Overall liking
banner %&gt;%  
    tab_cells(h22) %&gt;% 
    tab_means_sig() %&gt;% 
    tab_cpct_sig() %&gt;%  
    tab_cells(p22) %&gt;% 
    tab_means_sig() %&gt;% 
    tab_cpct_sig() %&gt;%
    tab_pivot() </code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Age&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='5' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Preferences&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='1' style='font-weight: 900; text-align: center;'></th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;18 - 25&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;26 - 35&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;VSX123&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;SDF456&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Hard to say&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>A</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>B</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>A</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>B</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>C</b>&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='12' style='font-weight: 900;'>&nbsp;Overall quality. VSX123&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;<b><u>Mean</u></b>&nbsp;</td>
<td style='text-align: right;'>  5.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.6</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.8 <b>A</b></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>5.5</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Extremely poor&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Very poor&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Quite poor&nbsp;</td>
<td style='text-align: right;'> 2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.2        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 3.2        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Neither good, nor poor&nbsp;</td>
<td style='text-align: right;'>10.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>11.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>10.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>14.9 <b>B</b></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Quite good&nbsp;</td>
<td style='text-align: right;'>39.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>45.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.8        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>40.4        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>38.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.3</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Very good&nbsp;</td>
<td style='text-align: right;'>33.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>24.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>41.2 <b>A</b></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>30.9        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>38.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.3</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Excellent&nbsp;</td>
<td style='text-align: right;'>14.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>15.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>13.8        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>10.6        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>22.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='text-align: right;'>150</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>70</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>80        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>94        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>6</td>
</tr> 
<tr><td colspan='12' style='font-weight: 900;'>&nbsp;Overall quality. SDF456&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;<b><u>Mean</u></b>&nbsp;</td>
<td style='text-align: right;'>  5.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>5.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Extremely poor&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Very poor&nbsp;</td>
<td style='text-align: right;'> 0.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Quite poor&nbsp;</td>
<td style='text-align: right;'> 2.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 4.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 4.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Neither good, nor poor&nbsp;</td>
<td style='text-align: right;'>16.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>20.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>13.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>18.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>14.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Quite good&nbsp;</td>
<td style='text-align: right;'>31.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>27.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>35.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>28.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>38.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Very good&nbsp;</td>
<td style='text-align: right;'>35.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>35.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>35.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>35.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>34.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Excellent&nbsp;</td>
<td style='text-align: right;'>13.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>12.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>13.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>14.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>10.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>150</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>70</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>80</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>94</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>50</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>6</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Likes
banner %&gt;% 
    tab_cells(h_likes) %&gt;% 
    tab_means_sig() %&gt;% 
    tab_cells(mrset(h1_1 %to% h1_6)) %&gt;% 
    tab_cpct_sig() %&gt;% 
    tab_cells(p_likes) %&gt;% 
    tab_means_sig() %&gt;% 
    tab_cells(mrset(p1_1 %to% p1_6)) %&gt;% 
    tab_cpct_sig() %&gt;%
    tab_pivot() </code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Age&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='5' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Preferences&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='1' style='font-weight: 900; text-align: center;'></th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;18 - 25&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;26 - 35&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;VSX123&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;SDF456&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='1' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Hard to say&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>A</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>B</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>A</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>B</b>&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;<b>C</b>&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='12' style='font-weight: 900;'>&nbsp;Number of likes. VSX123&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;<b><u>Mean</u></b>&nbsp;</td>
<td style='text-align: right;'>  2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>2.3</td>
</tr> 
<tr><td colspan='12' style='font-weight: 900;'>&nbsp;Likes. VSX123&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Liked everything&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>                 </td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Disliked everything&nbsp;</td>
<td style='text-align: right;'> 3.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 4.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>                 </td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Chocolate&nbsp;</td>
<td style='text-align: right;'>34.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>38.6</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>30.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>35.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>32.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.3                 &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Appearance&nbsp;</td>
<td style='text-align: right;'>29.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>21.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>36.2 <b>A</b></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>25.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>38.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7                 &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Taste&nbsp;</td>
<td style='text-align: right;'>32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>38.6</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>26.2        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>23.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>48.0 <b>A</b></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.3                 &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Stuffing&nbsp;</td>
<td style='text-align: right;'>27.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>20.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.8        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>28.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>26.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7                 &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Nuts&nbsp;</td>
<td style='text-align: right;'>66.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>72.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>61.3        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>69.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>60.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>83.3                 &nbsp;</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Consistency&nbsp;</td>
<td style='text-align: right;'>12.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 4.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>18.8 <b>A</b></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 8.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>14.0        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50.0 <b>A</b> <b>B</b></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Other&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>                 </td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Hard to answer&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>        </td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>                 </td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='text-align: right;'>150</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>70</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>80        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>94</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50        &nbsp;</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>6                 &nbsp;</td>
</tr> 
<tr><td colspan='12' style='font-weight: 900;'>&nbsp;Number of likes. SDF456&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;<b><u>Mean</u></b>&nbsp;</td>
<td style='text-align: right;'>  2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>2.0</td>
</tr> 
<tr><td colspan='12' style='font-weight: 900;'>&nbsp;Likes. SDF456&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Liked everything&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Disliked everything&nbsp;</td>
<td style='text-align: right;'> 1.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.4</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 2.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Chocolate&nbsp;</td>
<td style='text-align: right;'>32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>27.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>36.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>29.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>34.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Appearance&nbsp;</td>
<td style='text-align: right;'>32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>35.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>28.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>34.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>30.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Taste&nbsp;</td>
<td style='text-align: right;'>39.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>42.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>36.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>36.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>44.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Stuffing&nbsp;</td>
<td style='text-align: right;'>27.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>24.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>30.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>31.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>20.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Nuts&nbsp;</td>
<td style='text-align: right;'>61.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>60.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>62.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>58.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>68.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Consistency&nbsp;</td>
<td style='text-align: right;'>10.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 5.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>13.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>11.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 6.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Other&nbsp;</td>
<td style='text-align: right;'> 0.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'> 1.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;Hard to answer&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>150</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>70</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>80</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>94</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>50</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>6</td>
</tr>
</tbody>
</table>
<pre class="r"><code># below more complciated table were we compare likes side by side
# Likes - side by side comparison
w %&gt;% 
    tab_cols(total(label = &quot;#Total| |&quot;), c1r) %&gt;% 
    tab_cells(list(unvr(mrset(h1_1 %to% h1_6)))) %&gt;% 
    tab_stat_cpct(label = var_lab(h1_1)) %&gt;% 
    tab_cells(list(unvr(mrset(p1_1 %to% p1_6)))) %&gt;% 
    tab_stat_cpct(label = var_lab(p1_1)) %&gt;% 
    tab_pivot(stat_position = &quot;inside_columns&quot;) </code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;#Total&nbsp;</th><th style='border-top: 2px solid grey;; border-bottom: hidden;'>&nbsp;</th>
<th colspan='8' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Preferences&nbsp;</th>
</tr>
<tr>
<th style=''></th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp; &nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;VSX123&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;SDF456&nbsp;</th><th style='; border-bottom: hidden;'>&nbsp;</th>
<th colspan='2' style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'>&nbsp;Hard to say&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Likes. VSX123&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Likes. SDF456&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Likes. VSX123&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Likes. SDF456&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Likes. VSX123&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Likes. SDF456&nbsp;</th>
<th style='border-bottom: 1px solid grey;' colspan='1'>&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Likes. VSX123&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;Likes. SDF456&nbsp;</th>
</tr>
</thead>
<tbody>
<tr>
<td style='text-align: left;'>&nbsp;Liked everything&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Disliked everything&nbsp;</td>
<td style='text-align: right;'>3.3</td>
<td style='text-align: right;'>1.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>4.3</td>
<td style='text-align: right;'>2.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>2</td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Chocolate&nbsp;</td>
<td style='text-align: right;'>34.0</td>
<td style='text-align: right;'>32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>35.1</td>
<td style='text-align: right;'>29.8</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>32</td>
<td style='text-align: right;'>34</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.3</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Appearance&nbsp;</td>
<td style='text-align: right;'>29.3</td>
<td style='text-align: right;'>32.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>25.5</td>
<td style='text-align: right;'>34.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>38</td>
<td style='text-align: right;'>30</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Taste&nbsp;</td>
<td style='text-align: right;'>32.0</td>
<td style='text-align: right;'>39.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>23.4</td>
<td style='text-align: right;'>36.2</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>48</td>
<td style='text-align: right;'>44</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>33.3</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Stuffing&nbsp;</td>
<td style='text-align: right;'>27.3</td>
<td style='text-align: right;'>27.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>28.7</td>
<td style='text-align: right;'>31.9</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>26</td>
<td style='text-align: right;'>20</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>16.7</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Nuts&nbsp;</td>
<td style='text-align: right;'>66.7</td>
<td style='text-align: right;'>61.3</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>69.1</td>
<td style='text-align: right;'>58.5</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>60</td>
<td style='text-align: right;'>68</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>83.3</td>
<td style='text-align: right;'>50.0</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Consistency&nbsp;</td>
<td style='text-align: right;'>12.0</td>
<td style='text-align: right;'>10.0</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>8.5</td>
<td style='text-align: right;'>11.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>14</td>
<td style='text-align: right;'>6</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'>50.0</td>
<td style='text-align: right;'>16.7</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Other&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'>0.7</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'>1.1</td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;Hard to answer&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
<td style='' colspan='1'>&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>150</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>150</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>94</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>94</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>50</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>50</td>
<td style='border-bottom: 2px solid grey;' colspan='1'>&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>6</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>6</td>
</tr>
</tbody>
</table>
<p>We can save labelled dataset as *.csv file with accompanying R code for labelling.</p>
<pre class="r"><code>write_labelled_csv(w, file  filename = &quot;product_test.csv&quot;)</code></pre>
<p>Or, we can save dataset as *.csv file with SPSS syntax to read data and apply labels.</p>
<pre class="r"><code>write_labelled_spss(w, file  filename = &quot;product_test.csv&quot;)</code></pre>
</div>
<div id="labels-support-for-base-r" class="section level2">
<h2>Labels support for base R</h2>
<p>Here we demonstrate labels support in base R - value labels automatically used as factors levels. So every function which converts labelled variable to factor will utilize labels.</p>
<pre class="r"><code>library(knitr)</code></pre>
<pre><code>## Warning: package &#39;knitr&#39; was built under R version 3.4.2</code></pre>
<pre class="r"><code>with(mtcars, table(am, vs))</code></pre>
<pre><code>##            vs
## am          V-engine Straight engine
##   Automatic       12               7
##   Manual           6               7</code></pre>
<pre class="r"><code>boxplot(mpg ~ am, data = mtcars)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>There is a special function for variables labels support - <code>use_labels</code>. By now variables labels support available only for expression which will be evaluated inside data.frame.</p>
<pre class="r"><code># table with dimension names
use_labels(mtcars, table(am, vs)) </code></pre>
<pre><code>##             Engine
## Transmission V-engine Straight engine
##    Automatic       12               7
##    Manual           6               7</code></pre>
<pre class="r"><code># linear regression
use_labels(mtcars, lm(mpg ~ wt + hp + qsec)) %&gt;% summary</code></pre>
<pre><code>## 
## Call:
## lm(formula = `Miles/(US) gallon` ~ `Weight (1000 lbs)` + `Gross horsepower` + 
##     `1/4 mile time`)
## 
## Residuals:
## LABEL: Miles/(US) gallon 
## VALUES:
## -3.8591, -1.6418, -0.4636, 1.194, 5.6092
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         27.61053    8.41993   3.279  0.00278 ** 
## `Weight (1000 lbs)` -4.35880    0.75270  -5.791 3.22e-06 ***
## `Gross horsepower`  -0.01782    0.01498  -1.190  0.24418    
## `1/4 mile time`      0.51083    0.43922   1.163  0.25463    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.578 on 28 degrees of freedom
## Multiple R-squared:  0.8348, Adjusted R-squared:  0.8171 
## F-statistic: 47.15 on 3 and 28 DF,  p-value: 4.506e-11</code></pre>
<p>And, finally, <code>ggplot2</code> graphics with variables and value labels:</p>
<pre class="r"><code>library(ggplot2)
use_labels(mtcars, {
    # &#39;vars(other)&#39; is needed to get all &#39;mtcars&#39; data.frame inside expression 
    ggplot(vars(other)) +
        geom_point(aes(y = mpg, x = wt, color = qsec)) +
        facet_grid(am ~ vs)
}) </code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
<div id="excel-functions-translation-guide" class="section level2">
<h2>Excel functions translation guide</h2>
<p>Excel toy table:</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">A</th>
<th align="right">B</th>
<th align="right">C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>1</strong></td>
<td align="right">2</td>
<td align="right">15</td>
<td align="right">50</td>
</tr>
<tr class="even">
<td align="left"><strong>2</strong></td>
<td align="right">1</td>
<td align="right">70</td>
<td align="right">80</td>
</tr>
<tr class="odd">
<td align="left"><strong>3</strong></td>
<td align="right">3</td>
<td align="right">30</td>
<td align="right">40</td>
</tr>
<tr class="even">
<td align="left"><strong>4</strong></td>
<td align="right">2</td>
<td align="right">30</td>
<td align="right">40</td>
</tr>
</tbody>
</table>
<p>Code for creating the same table in R:</p>
<pre class="r"><code>w = from_text(&quot;
    a  b  c
    2 15 50
    1 70 80
    3 30 40
    2 30 40
&quot;)</code></pre>
<p><code>w</code> is the name of our table.</p>
<div id="if" class="section level5">
<h5>IF</h5>
<p><strong>Excel: <code>IF(B1&gt;60, 1, 0)</code></strong></p>
<p><strong>R:</strong> Here we create new column with name <code>d</code> with results. <code>ifelse</code> function is from base R not from ‘expss’ package but included here for completeness.</p>
<pre class="r"><code>w$d = ifelse(w$b&gt;60, 1, 0)</code></pre>
<p>If we need to use multiple transformations it is often convenient to use <code>compute</code> function. Inside <code>compute</code> we can put arbitrary number of the statements:</p>
<pre class="r"><code>w = compute(w, {
    d = ifelse(b&gt;60, 1, 0)
    e = 42
    abc_sum = sum_row(a, b, c)
    abc_mean = mean_row(a, b, c)
})</code></pre>
</div>
<div id="countif" class="section level5">
<h5>COUNTIF</h5>
<p>Count 1’s in the entire dataset.</p>
<p><strong>Excel: <code>COUNTIF(A1:C4, 1)</code></strong></p>
<p><strong>R:</strong></p>
<pre class="r"><code>count_if(1, w)</code></pre>
<p>or</p>
<pre class="r"><code>calculate(w, count_if(1, a, b, c))</code></pre>
<p>Count values greater than 1 in each row of the dataset.</p>
<p><strong>Excel: <code>COUNTIF(A1:C1, &quot;&gt;1&quot;)</code></strong></p>
<p><strong>R</strong>:</p>
<pre class="r"><code>w$d = count_row_if(gt(1), w)  </code></pre>
<p>or</p>
<pre class="r"><code>w = compute(w, {
    d = count_row_if(gt(1), a, b, c) 
})</code></pre>
<p>Count values less than or equal to 1 in column A of the dataset.</p>
<p><strong>Excel: <code>COUNTIF(A1:A4, &quot;&lt;=1&quot;)</code></strong></p>
<p><strong>R</strong>:</p>
<pre class="r"><code>count_col_if(le(1), w$a)</code></pre>
<p><strong>Table of criteria:</strong></p>
<table>
<thead>
<tr class="header">
<th>Excel</th>
<th>R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“&lt;1”</td>
<td>lt(1)</td>
</tr>
<tr class="even">
<td>“&lt;=1”</td>
<td>le(1)</td>
</tr>
<tr class="odd">
<td>“&lt;&gt;1”</td>
<td>ne(1)</td>
</tr>
<tr class="even">
<td>“=1”</td>
<td>eq(1)</td>
</tr>
<tr class="odd">
<td>“&gt;=1”</td>
<td>ge(1)</td>
</tr>
<tr class="even">
<td>“&gt;1”</td>
<td>gt(1)</td>
</tr>
</tbody>
</table>
</div>
<div id="sumaverage" class="section level5">
<h5>SUM/AVERAGE</h5>
<p>Sum all values in the dataset.</p>
<p><strong>Excel: <code>SUM(A1:C4)</code></strong></p>
<p><strong>R:</strong></p>
<pre class="r"><code>sum(w, na.rm = TRUE)</code></pre>
<p>Calculate average of each row of the dataset.</p>
<p><strong>Excel: <code>AVERAGE(A1:C1)</code></strong></p>
<p><strong>R</strong>:</p>
<pre class="r"><code>w$d = mean_row(w)  </code></pre>
<p>or</p>
<pre class="r"><code>w = compute(w, {
    d = mean_row(a, b, c) 
})</code></pre>
<p>Sum values of column <code>A</code> of the dataset.</p>
<p><strong>Excel: <code>SUM(A1:A4)</code></strong></p>
<p><strong>R</strong>:</p>
<pre class="r"><code>sum_col(w$a)</code></pre>
</div>
<div id="sumifaverageif" class="section level5">
<h5>SUMIF/AVERAGEIF</h5>
<p>Sum values greater than 40 in the entire dataset.</p>
<p><strong>Excel: <code>SUMIF(A1:C4, &quot;&gt;40&quot;)</code></strong></p>
<p><strong>R:</strong></p>
<pre class="r"><code>sum_if(gt(40), w)</code></pre>
<p>or</p>
<pre class="r"><code>calculate(w, sum_if(gt(40), a, b, c))</code></pre>
<p>Sum values less than 40 in the each row of the dataset.</p>
<p><strong>Excel: <code>SUMIF(A1:C1, &quot;&lt;40&quot;)</code></strong></p>
<p><strong>R</strong>:</p>
<pre class="r"><code>w$d = sum_row_if(lt(40), w)  </code></pre>
<p>or</p>
<pre class="r"><code>w = compute(w, {
    d = sum_row_if(lt(40), a, b, c) 
})</code></pre>
<p>Calculate average of <code>B</code> column with column <code>A</code> values less than 3.</p>
<p><strong>Excel: <code>AVERAGEIF(A1:A4, &quot;&lt;3&quot;, B1:B4)</code></strong></p>
<p><strong>R</strong>:</p>
<pre class="r"><code>mean_col_if(lt(3), w$a, data = w$b)</code></pre>
<p>or, if we want calculate means for both <code>b</code> and <code>c</code> columns:</p>
<pre class="r"><code>calculate(w, mean_col_if(lt(3), a, data = sheet(b, c)))</code></pre>
</div>
<div id="vlookup" class="section level5">
<h5>VLOOKUP</h5>
<p>Our dictionary for lookup:</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">X</th>
<th align="left">Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>1</strong></td>
<td align="right">1</td>
<td align="left">apples</td>
</tr>
<tr class="even">
<td align="left"><strong>2</strong></td>
<td align="right">2</td>
<td align="left">oranges</td>
</tr>
<tr class="odd">
<td align="left"><strong>3</strong></td>
<td align="right">3</td>
<td align="left">peaches</td>
</tr>
</tbody>
</table>
<p>Code for creating the same dictionary in R:</p>
<pre class="r"><code>dict = from_text(&quot;
    x  y
    1  apples
    2  oranges
    3  peaches
&quot;)</code></pre>
<p><strong>Excel: <code>VLOOKUP(A1, $X$1:$Y$3, 2, FALSE)</code></strong></p>
<p><strong>R</strong>:</p>
<pre class="r"><code>w$d = vlookup(w$a, dict, 2)</code></pre>
<p>or, we can use column names:</p>
<pre class="r"><code>w$d = vlookup(w$a, dict, &quot;y&quot;)</code></pre>
</div>
</div>
<div id="spss-functions-translation-guide" class="section level2">
<h2>SPSS functions translation guide</h2>
<div id="compute" class="section level5">
<h5>COMPUTE</h5>
<p><strong>SPSS</strong>:</p>
<pre><code>COMPUTE d = 1.</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>w$d = 1</code></pre>
<p>or, in the specific data.frame</p>
<pre class="r"><code>w = compute(w, {
    d = 1
})</code></pre>
<p>There can be arbitrary number of statements inside <code>compute</code>.</p>
</div>
<div id="if-1" class="section level5">
<h5>IF</h5>
<p><strong>SPSS</strong>:</p>
<pre><code>IF(a = 3) d = 2.</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>w = compute(w, {
    d = ifelse(a == 3, 2, NA)
})</code></pre>
<p>or,</p>
<pre class="r"><code>w = compute(w, {
    d = ifs(a == 3 ~ 2)
})</code></pre>
</div>
<div id="do-if" class="section level5">
<h5>DO IF</h5>
<p><strong>SPSS</strong>:</p>
<pre><code>DO IF (a&gt;1).
    COMPUTE d = 4.
END IF.</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>w = do_if(w, a&gt;1, {
    d = 4
})</code></pre>
<p>There can be arbitrary number of statements inside <code>do_if</code>.</p>
</div>
<div id="count" class="section level5">
<h5>COUNT</h5>
<p><strong>SPSS</strong>:</p>
<pre><code>COUNT cnt = a1 TO a5 (LO THRU HI).</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>cnt = count_row_if(lo %thru% hi, a1 %to% a5)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>COUNT cnt = a1 TO a5 (SYSMIS).</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>cnt = count_row_if(NA, a1 %to% a5)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>COUNT cnt = a1 TO a5 (1 THRU 5).</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>cnt = count_row_if(1 %thru% 5, a1 %to% a5)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>COUNT cnt = a1 TO a5 (1 THRU HI).</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>cnt = count_row_if(1 %thru% hi, a1 %to% a5)</code></pre>
<p>or,</p>
<pre class="r"><code>cnt = count_row_if(ge(1), a1 %to% a5)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>COUNT cnt = a1 TO a5 (LO THRU 1).</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>cnt = count_row_if(lo %thru% 1, a1 %to% a5)</code></pre>
<p>or,</p>
<pre class="r"><code>cnt = count_row_if (le(1), a1 %to% a5)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>COUNT cnt = a1 TO a5 (1 THRU 5, 99).</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>cnt = count_row_if(1 %thru% 5 | 99, a1 %to% a5)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>COUNT cnt = a1 TO a5(1,2,3,4,5, SYSMIS).</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>cnt = count_row_if(c(1:5, NA), a1 %to% a5)</code></pre>
<p><code>count_row_if</code> can be used inside <code>compute</code>.</p>
</div>
<div id="recode" class="section level5">
<h5>RECODE</h5>
<p><strong>SPSS</strong>:</p>
<pre><code>RECODE V1 (0=1) (1=0) (2, 3=-1) (9=9) (ELSE=SYSMIS)</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>recode(v1) = c(0 ~ 1, 1 ~ 0, 2:3 ~ -1, 9 ~ 9, other ~ NA)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>RECODE QVAR(1 THRU 5=1)(6 THRU 10=2)(11 THRU HI=3)(ELSE=0).</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>recode(qvar) = c(1 %thru% 5 ~ 1, 6 %thru% 10 ~ 2, 11 %thru% hi ~ 3, other ~ 0)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>RECODE STRNGVAR (&#39;A&#39;, &#39;B&#39;, &#39;C&#39;=&#39;A&#39;)(&#39;D&#39;, &#39;E&#39;, &#39;F&#39;=&#39;B&#39;)(ELSE=&#39; &#39;). </code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>recode(strngvar) = c(c(&#39;A&#39;, &#39;B&#39;, &#39;C&#39;) ~ &#39;A&#39;, c(&#39;D&#39;, &#39;E&#39;, &#39;F&#39;) ~ &#39;B&#39;, other ~ &#39; &#39;)</code></pre>
<p><strong>SPSS</strong>:</p>
<pre><code>RECODE AGE (MISSING=9) (18 THRU HI=1) (0 THRU 18=0) INTO VOTER. </code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>voter = recode(age, NA ~ 9, 18 %thru% hi ~ 1, 0 %thru% 18 ~ 0)
# or
recode(age, NA ~ 9, 18 %thru% hi ~ 1, 0 %thru% 18 ~ 0) %into% voter</code></pre>
<p><code>recode</code> can be used inside <code>compute</code>.</p>
</div>
<div id="variable-labels" class="section level5">
<h5>VARIABLE LABELS</h5>
<p><strong>SPSS</strong>:</p>
<pre><code>VARIABLE LABELS a &quot;Fruits&quot;
                b &quot;Cost&quot;
                c &quot;Price&quot;.</code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>w = apply_labels(w,
                 a = &quot;Fruits&quot;,
                 b = &quot;Cost&quot;,
                 c = &quot;Price&quot;
)</code></pre>
</div>
<div id="value-labels" class="section level5">
<h5>VALUE LABELS</h5>
<p><strong>SPSS</strong>:</p>
<pre><code>VALUE LABELS a
    1 &quot;apples&quot;
    2 &quot;oranges&quot;
    3 &quot;peaches&quot;. </code></pre>
<p><strong>R</strong>:</p>
<pre class="r"><code>w = apply_labels(w, 
                 a = num_lab(&quot;
                        1 apples
                        2 oranges
                        3 peaches 
                    &quot;)
)</code></pre>
<p>or,</p>
<pre class="r"><code>val_lab(w$a) = num_lab(&quot;
    1 apples
    2 oranges
    3 peaches 
&quot;)</code></pre>
</div>
<div id="tables" class="section level5">
<h5>Tables</h5>
<p><strong>R</strong>:</p>
<pre class="r"><code>fre(w$a) # Frequency of fruits</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>Fruits</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Count&nbsp;</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Valid percent&nbsp;</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Percent&nbsp;</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Responses, %&nbsp;</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Cumulative responses, %&nbsp;</th>
</tr>
</thead>
<tbody>
<tr>
<td style='text-align: left;'>&nbsp;apples&nbsp;</td>
<td style='text-align: right;'>1</td>
<td style='text-align: right;'>25</td>
<td style='text-align: right;'>25</td>
<td style='text-align: right;'>25</td>
<td style='text-align: right;'>25</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;oranges&nbsp;</td>
<td style='text-align: right;'>2</td>
<td style='text-align: right;'>50</td>
<td style='text-align: right;'>50</td>
<td style='text-align: right;'>50</td>
<td style='text-align: right;'>75</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;peaches&nbsp;</td>
<td style='text-align: right;'>1</td>
<td style='text-align: right;'>25</td>
<td style='text-align: right;'>25</td>
<td style='text-align: right;'>25</td>
<td style='text-align: right;'>100</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;#Total&nbsp;</td>
<td style='text-align: right;'>4</td>
<td style='text-align: right;'>100</td>
<td style='text-align: right;'>100</td>
<td style='text-align: right;'>100</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&lt;NA&gt;&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>0</td>
<td style='border-bottom: 2px solid grey; text-align: right;'></td>
<td style='border-bottom: 2px solid grey; text-align: right;'>0</td>
<td style='border-bottom: 2px solid grey; text-align: right;'></td>
<td style='border-bottom: 2px solid grey; text-align: right;'></td>
</tr>
</tbody>
</table>
<pre class="r"><code>cro_cpct(w$b, w$a) # Column percent of cost by fruits</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Fruits&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;apples&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;oranges&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;peaches&nbsp;</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='4' style='font-weight: 900;'>&nbsp;Cost&nbsp;</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;15&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'>50</td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;30&nbsp;</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'>50</td>
<td style='text-align: right;'>100</td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;&nbsp;70&nbsp;</td>
<td style='text-align: right;'>100</td>
<td style='text-align: right;'></td>
<td style='text-align: right;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;&nbsp;#Total cases&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>1</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>2</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>1</td>
</tr>
</tbody>
</table>
<pre class="r"><code>cro_mean(sheet(w$b, w$c), w$a) # Mean cost and price by fruits</code></pre>
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-top: 2px solid grey;'></th>
<th colspan='3' style='font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>&nbsp;Fruits&nbsp;</th>
</tr>
<tr>
<th style='font-weight: 900; border-bottom: 1px solid grey; text-align: center;'></th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;apples&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;oranges&nbsp;</th>
<th style='border-bottom: 1px solid grey; text-align: center;'>&nbsp;peaches&nbsp;</th>
</tr>
</thead>
<tbody>
<tr>
<td style='text-align: left;'>&nbsp;Cost&nbsp;</td>
<td style='text-align: right;'>70</td>
<td style='text-align: right;'>22.5</td>
<td style='text-align: right;'>30</td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;Price&nbsp;</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>80</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>45.0</td>
<td style='border-bottom: 2px solid grey; text-align: right;'>40</td>
</tr>
</tbody>
</table>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
